package org.msh.eventbus;

/**
 * Handle events generated by the {@link EventBusService}
 * 
 * @author Ricardo Memoria
 *
 */
public interface EventBusListener {

	/**
	 * Method that will receive information about an event
	 * @param event
	 * @param data
	 */
	void handleEvent(Object event, Object... data);
}
