package org.msh.etbm.sync;

/**
 * Just to identity exceptions that are generated by the server
 * Created by ricardo on 27/07/14.
 */
public class ServerException extends RuntimeException {

    public ServerException() {
    }

    public ServerException(String message) {
        super(message);
    }

    public ServerException(String message, Throwable cause) {
        super(message, cause);
    }

    public ServerException(Throwable cause) {
        super(cause);
    }

}
